### PR TITLE
integration of OCCInterface

### PR DESCRIPTION
**Pull request by Romathonat**

### CODE REVIEW

**Comment by jeanparpaillon** [comment]
Thanks for the contrib
* Your npm build fails in travis, can you have a look ?:
https://travis-ci.org/erocci/erocci/jobs/155079472
* It may be better to fix the version of erocci_frontend in the Makefile

**Comment by Romathonat** [comment]
- it seems travis does not have a recent version of npm? It does not find a recent version of express-proxy. I think travis is configured with erlang, but not node so the version is the default wich is too old.
- the version is not fixed (master), why do you want it to be?

**Comment by Romathonat** [comment]
I manually forced the download of node, now it works.

**Comment by jeanparpaillon** [comment]
Great for fixing nodejs build.

Regarding fixing version, it allows reproducible builds. If one component of erocci fails to build, fixing version prevent breaking erocci, while fetching 'master' for every component will break erocci every time one component breaks.

erocci's Makefile has a 'lock' target to update the `deps.lock` file with current version of each component.

BTW, when developing, you can manually update the version of your components (including erocci_frontend).

**Pull request merged**
